language: java
jdk:
- oraclejdk8
script: ant build
addons:
  sonarcloud:
    organization: "jeevan1133-github" # the key of the org you chose at step #3
    token:
      secure: 51ac53b75c711b05920f3f7f06af9c901a4054ce  # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
mvn sonar:sonar \
  -Dsonar.projectKey=fishheadsproject \
  -Dsonar.organization=jeevan1133-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=31cd198ce31f24b591e5bd753d5cc6b5f34725f5
